services:
  bot:
    image: whitelist_telegram_bot
    container_name: whitelist_telegram_bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    tty: true
    env_file: .env
    volumes:
      - .:/code
